### ISSUE TITLE
Request for Access to Synthetic Dataset (MVTec-AD)

### ISSUE THREAD

**Issue by Kathy1214** [HY-Vision-Lab/FUNAD#2]
I really appreciate the work you’ve done with this project—it's incredibly inspiring!

I noticed that the link to the Synthetic dataset (MVTec-AD) ([Our Link]) is currently broken, and the file seems to be unavailable. I was wondering if you could kindly share the dataset or provide an alternative link to access it?

Thank you for your time and consideration!

**Comment by hy-yhson** [comment]
We appreciate your interest in our work. 
The link to the synthetic dataset has been updated and is now available for download.
Thank you.
